### ISSUE TITLE
For issues, handbook/help.html#report-a-bug directs users to a repository that no longer allows issues

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina-docs#13]
https://www.trueos.org/handbook/help.html#report-a-bug

> … If you are in doubt, select the “trueos-utils-qt5” repository. …
## Problem

https://github.com/trueos/trueos-utils-qt5/issues no longer exists, there's a redirect to https://github.com/trueos/trueos-utils-qt5/pulls

**Comment by dlavigne** [comment]
This has already been fixed: https://github.com/trueos/trueos-docs/commit/346231d833cb79430eca30cbecc5aa3041f3c964.
