### ISSUE TITLE
For as long as panels may not be opaque, the handbook should not state that a panel "may" be transparent

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina-docs#15]
No rush for https://github.com/trueos/lumina/issues/347 but for as long as all panels **must** be transparent, the handbook should not use the word "may". 

From [post 5](https://discourse.trueos.org/t/how-to-make-a-panel-opaque/376/5?u=grahamperrin) under _How to make a panel opaque?_:

> For as long as there's no user preference, there should be a change to the wording at https://lumina-desktop.org/handbook/luminaconfig.html#panels:
> 
>> … Panels must be aligned along a screen edge, opposite screen edges in the case of two panels, and may have any width, color, or transparency. … 
> 
> – if a panel _may_ have transparency, then there should be a _may not_.

**Comment by Mrt134** [comment]
I added a short clarification about alpha channels to the appropriate section in the Handbook. Thanks for reporting this!
